### ISSUE TITLE
protocols vs concrete types

### ISSUE THREAD

**Issue by paulofaria** [swiftx/s4#15]
Basically we have two kinds of types in S4.

Data types:

Types that simply hold information in a structured manner. For example, a collection of bytes, URI, HTTP response, etc.

Behaviour types:

Types that manipulate information based on a pre-defined behaviour. For example, streams, http servers, routers, etc.

I think we all agree that behaviour types should definitely be protocols. But I'm not sure about data types.

Data types could be either protocols or concrete types. I think it's very important to discuss the advantages and disadvantages of both approaches, as this will guide a lot of decisions we take regarding S4 types.

**Comment by tannernelson** [comment]
I think protocols give the end users of S4 the most freedom. 

For example, if an implementation conforming to S4 wants reference semantics on their Requests, they would have to convert their instance of Request class into an S4.Request Struct instead of being able to simply pass their Request in. 

Protocols give the implementer the freedom to do whatever they want and whatever makes sense for their library. And it's what I think Swift intended protocols for.

**Comment by bradhilton** [comment]
One of the perceived disadvantages of using protocols instead of concrete types is that protocols can't conform to other protocols. While that's true, protocols can provide implementations for other protocols in where clauses and if it's especially important that a data type implement other protocols we can always use protocol inheritance. I'd like to see some examples where either using protocol extensions or protocol inheritance would be undesirable. For now I'm leaning towards protocols.

**Comment by bradhilton** [comment]
In fact I'm leaning towards making nearly everything a protocol. Zewo can write its implementation and Vapor its own with their preferences for value types vs. reference types.

**Comment by paulofaria** [comment]
> While that's true, protocols can provide implementations for other protocols in where clauses.

That wouldn't work.

Say we have this in S4:

```swift
public protocol HTTPRequest: HTTPMessage {
    var method: HTTPMethod { get set }
    var uri: URI { get set }
}

public protocol HTTPResponse: HTTPMessage {
    var status: HTTPStatus { get }
}
```

And we have a `LogMiddleware` package with this:

```swift
import S4

extension HTTPRequest where Self: CustomStringConvertible {
    var description: String {
        return "\(method) \(uri)"
    }
}

extension HTTPResponse where Self: CustomStringConvertible {
    var description: String {
        return "\(status.statusCode) \(status.reasonPhrase)"
    }
}

public struct LogMiddleware: HTTPMiddleware {
    public func respond(request: HTTPRequest, chain: HTTPResponder) throws -> HTTPResponse {
        let response = try chain.respond(request)
        print(request.description)
        print(response.description)
        return response
    }
}
```

That outputs:

```
error: type 'HTTPRequest' does not conform to protocol 'CustomStringConvertible'
        message += "\(request.description)\n"
error: type 'HTTPResponse' does not conform to protocol 'CustomStringConvertible'
        message += "\(response.description)\n"
```

---

If we make the protocol itself inherit from `CustomStringConvertible`:

Say we have this in S4:

```swift
public protocol HTTPRequest: HTTPMessage, CustomStringConvertible {
    var method: HTTPMethod { get set }
    var uri: URI { get set }
}

public protocol HTTPResponse: HTTPMessage, CustomStringConvertible {
    var status: HTTPStatus { get }
}
```

And we have a `LogMiddleware` package with this:

```swift
import S4

public struct LogMiddleware: HTTPMiddleware {
    public func respond(request: HTTPRequest, chain: HTTPResponder) throws -> HTTPResponse {
        let response = try chain.respond(request)
        print(request.description)
        print(response.description)
        return response
    }
}
```

That would work, but that's not flexible, cause S4 would have to define the protocols HTTPRequest and HTTPResponse protocols inherit from. So in this regard protocols are not flexible.

---

Now if we use concrete types ( `struct` or a `class`)

```swift
public struct HTTPRequest: HTTPMessage {
    public var method: HTTPMethod
    public var uri: URI
    public var version: HTTPVersion
    public var headers: HTTPHeaders
    public var body: HTTPBody
    public var storage: Storage = [:]
}

public struct HTTPResponse: HTTPMessage {
    public var version: HTTPVersion
    public var status: HTTPStatus
    public var headers: HTTPHeaders
    public var body: HTTPBody
    public var storage: Storage = [:]
}
```

And we have a `LogMiddleware` package with this:

```swift
import S4

extension HTTPRequest: CustomStringConvertible {
    public var description: String {
        return "\(method) \(uri)"
    }
}

extension HTTPResponse: CustomStringConvertible {
    public var description: String {
        return "\(status.statusCode) \(status.reasonPhrase)"
    }
}

public struct LogMiddleware: HTTPMiddleware {
    public func respond(request: HTTPRequest, chain: HTTPResponder) throws -> HTTPResponse {
        let response = try chain.respond(request)
        print(request.description)
        print(response.description)
        return response
    }
}
```

This would work. So concrete types are more flexible than protocols in regard to protocol conformance in extensions.

**Comment by paulofaria** [comment]
Now about safety. What makes protocols look more flexible for **data types**, is that they allow the type implementation to be a **value type** or a **reference type**. IMO this is a **disadvantage** cause this **duality** could be a big source of **bugs**, as one implementation could expect a reference type and another one a value type. So this two kinds of implementations are **incompatible**. We're looking for a **standard** here. So having code that adheres to a standard and is not compatible with code that also adheres to the same standard simply doesn't make sense.

Say we have this in S4:

```swift
public protocol HTTPRequest: HTTPMessage {
    var method: HTTPMethod { get set }
    var uri: URI { get set }
}

public protocol HTTPResponse: HTTPMessage {
    var status: HTTPStatus { get }
}
````

And we have a `ContentNegotiationMiddleware` package with this:

````swift
import S4

public struct LogMiddleware: HTTPMiddleware {
    public func respond(request: HTTPRequest, chain: HTTPResponder) throws -> HTTPResponse {
        var response = try chain.proceed(request)

        if let content = response.content {
            let mediaTypes = request.accept.count > 0 ? request.accept : self.mediaTypes
            let (mediaType, body) = try serialize(content, mediaTypes: mediaTypes)
            response.contentType = mediaType
            response.body = body
        }

        return response
    }
}
```

This implementation expects request to have value type semantics. So if the request has reference type semantics, when you pass the request along the chain:

```swift
var response = try chain.proceed(request)
```

Some other element in the chain could modify the request, for example changing the `accept` header. So this line:

```swift
let mediaTypes = request.accept.count > 0 ? request.accept : self.mediaTypes
````

Could not (and probably won't) reflect the request as it reached `ContentNegotiationMiddleware`.

We could protect ourselves from this by doing:

````swift
import S4

public struct LogMiddleware: HTTPMiddleware {
    public func respond(request: HTTPRequest, chain: HTTPResponder) throws -> HTTPResponse {
        let requestCopy = request.copy()
        var response = try chain.proceed(request)

        if let content = response.content {
            let mediaTypes = requestCopy.accept.count > 0 ? requestCopy.accept : self.mediaTypes
            let (mediaType, body) = try serialize(content, mediaTypes: mediaTypes)
            response.contentType = mediaType
            response.body = body
        }

        return response
    }
}
```

This would copy the request as it got to `ContentNegotiationMiddleware`:

```swift
let requestCopy = request.copy()
```

But for this to be possible all implementations of `HTTPRequest` would have to implement the `copy()` function. Even `structs` which are already copy-by-value. So in the end we're adding more code and more complexity everywhere and getting no flexibility, cause we would have to protect from value type semantics or reference type semantics, which would only be more confusing and make compatibility a nightmare. If we chose a concrete type for **data types** all of this could be avoided. Now if we go for value type semantics or reference type semantics is a whole other issue. My point here is we should go for concrete type instead of protocols for **data types**.

**Comment by bradhilton** [comment]
That's true, it would require type-casting the protocol to check for conformance at the use site, which would be less than ideal. However, that being said, Zewo, Vapor and others that write their own implementations of the standards, they could have their own protocols that can incorporate their framework types:
```swift
import S4

protocol Middleware : S4.Middleware {
    
    func respond(request: Zewo.Request, chain: Zewo.Responder) throws -> Zewo.Response
    func respond(standardRequest standardRequest: S4.Request, chain: S4.Responder) throws -> S4.Response
    
}

extension Middleware {
    
    func respond(request: S4.Request, chain: S4.Responder) throws -> S4.Response {
        guard let request = request as? Zewo.Request, chain = chain as? Zewo.Responder else {
            return try respond(standardRequest: request, chain: chain)
        }
        return try respond(request, chain: chain)
    }
    
}
```

I agree though that that is a strong argument for concrete types, but it could be managed.

**Comment by bradhilton** [comment]
```So in the end we're adding more code and more complexity everywhere and getting no flexibility, cause we would have to protect from value type semantics or reference type semantics, which would only be more confusing and make compatibility a nightmare. If we chose a concrete type for data types all of this could be avoided.```
Another strong argument for concrete types.

**Comment by paulofaria** [comment]
There's also the issue that protocols can't be keys to dictionaries. Yes we could add more code to make that possible. But that goes with what I said before about adding more code and more complexity to solve this issue.

**Comment by bradhilton** [comment]
I think I'm siding with Paulo now, but we should get more input from Logan and Tanner.

**Comment by paulofaria** [comment]
Actually we should get more input from the world haha. What do we need to go public?

**Comment by LoganWright** [comment]
For this:

```Swift
public protocol HTTPRequest: HTTPMessage, CustomStringConvertible {
    var method: HTTPMethod { get set }
    var uri: URI { get set }
}

public protocol HTTPResponse: HTTPMessage, CustomStringConvertible {
    var status: HTTPStatus { get }
}
```

We could easily add:

```Swift
extension HTTPResponse {
    var description: String {
        return "asdf"
    }
}
```

Which seems to accomplish the same thing as an enforced concrete ype

**Comment by tannernelson** [comment]
If you make `S4.Response` a `struct` then the only way Vapor would implement that is having something like 

```
extension Vapor.Response {
    func toS4Response() -> S4.Response {
         //create S4.Response here
    }
}
```

Because Vapor, and I'm sure any other framework, would not want to do the major refactoring it would take to do `Vapor.Request: S4.Request`.

So if we're okay with people needing to do that then why not have an `S4.ResponseConvertible` protocol that would make it more standard. Then we're back to having a protocol.

**Comment by LoganWright** [comment]
Concrete types w/ Convertible protocols seems to be the current consensus
