### ISSUE TITLE
Modularity vs Namespacing

### ISSUE THREAD

**Issue by paulofaria** [swiftx/s4#2]
Hi, everyone!

I'm raising the discussion about modularity vs namespacing. The options would be.

## Single Module

We would have only **one** module called `S4` which would have **all** protocols defined by the standard. Some protocols would need to have a prefix namespace like:

- `HTTPRequestType`
- `HTTPResponseType`
- `HTTPResponderType`
- `HTTPServer`
- etc.

Also if you're writing a framework that uses just one protocol you would be forced to have everything. Having one module would also make the development easier, since we wouldn't need to worry about syncing tags across all modules, etc.

## Multiple Modules

With multiple modules the protocols wouldn't need the prefix on the types cause they would be namespaced to the module. The downside would be a lot of imports in case you depend on lots of modules, but this could be mitigated with an umbrella header and the `@_exported` attribute. It would be harder to maintain, but that could be mitigated using a tool. Maybe we would have to prefix the module itself, like, `S4HTTP`, `S4Stream`, so we don't clash with other modules.

What do you think it's best? Have any other suggestion or upsides and downsides that could be added?

**Comment by tannernelson** [comment]
I'd say given the current limitations of SPM and also simplicity, one module. I don't think we will be adding anything besides HTTP soon. So we can cross that bridge when we get there.

**Comment by paulofaria** [comment]
I think one module with namespace would be ok. If you don't like it, simply `typealias` it in your framework.

**Comment by tannernelson** [comment]
My vote is `S4.HTTPRequest`

**Comment by paulofaria** [comment]
Considering we might support db protocols this topic woke up from the dead.

**Comment by paulofaria** [comment]
I think we should have only one package called `SwiftX` with everything.

**Comment by antonmes** [comment]
+1 for SwiftX
